FROM node:20-alpine

WORKDIR /usr/src/app

COPY backend/package*.json ./

RUN npm install

COPY backend/ .

ENV MONGODB_URI = 'mongodb+srv://shubhsaxena447:E3VaJ3Hcu2mdvjFY@cluster0.hmcl9.mongodb.net'
ENV PORT = 3000
ENV REDIS_HOST=redis-16945.crce179.ap-south-1-1.ec2.redns.redis-cloud.com
ENV REDIS_PORT=16945
ENV REDIS_PASSWORD=GWEC1hn06dUlV5evNAfOKo2Rmlr7friJ
ENV CORS_ORIGIN = *

EXPOSE 3000

CMD ["npm", "run", "dev"]
